### ISSUE TITLE
OpenMM cannot load a larger inpcrd/prmtop

### ISSUE THREAD

**Issue by leeping** [pandegroup/openmm#101]
Hi there,

When building examples for the OpenMM command line program, I found that it can't load one of the larger AMBER example files.  First, it was unable to load the coordinates because the .inpcrd file had floats that were running together.  I was able to work around this by replacing the last decimal of precision with a space.  

Next, it wasn't able to load the .prmtop file with a more cryptic error message, which I wasn't able to solve.

The files are here:

https://dl.dropboxusercontent.com/u/5381783/dppc_128.inpcrd
https://dl.dropboxusercontent.com/u/5381783/dppc_128.prmtop

First error:
```
>>> inpcrd = app.AmberInpcrdFile('dppc_128.inpcrd')
Traceback (most recent call last):
  File "/home/leeping/local/bin/openmm", line 5, in <module>
    pkg_resources.run_script('openmm-cmd==0.1', 'openmm')
  File "/home/leeping/.local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
  File "/home/leeping/.local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 1018, in <module>
    openmm.start()
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 766, in start
    topology = self.general.get_topology()
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 253, in get_topology
    self.load_coords()
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 134, in load_coords
    self.inpcrd_file = app.AmberInpcrdFile(self.coords)
  File "/home/leeping/.local/lib/python2.7/site-packages/simtk/openmm/app/amberinpcrdfile.py", line 57, in __init__
    results = amber_file_parser.readAmberCoordinates(file, read_velocities=loadVelocities, read_box=loadBoxVectors)
  File "/home/leeping/.local/lib/python2.7/site-packages/simtk/openmm/app/internal/amber_file_parser.py", line 891, in readAmberCoordinates
    coordinates.append(mm.Vec3(float(elements.pop(0)), float(elements.pop(0)), float(elements.pop(0))))
ValueError: invalid literal for float(): -20.5102618-135.5159901
```

Second error:
```
>>> prmtop = app.AmberPrmtopFile('dppc_128.prmtop')
Traceback (most recent call last):
  File "/home/leeping/local/bin/openmm", line 5, in <module>
    pkg_resources.run_script('openmm-cmd==0.1', 'openmm')
  File "/home/leeping/.local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
  File "/home/leeping/.local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 1018, in <module>
    openmm.start()
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 766, in start
    topology = self.general.get_topology()
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 253, in get_topology
    self.load_coords()
  File "/home/leeping/local/lib/python2.7/site-packages/openmm_cmd-0.1-py2.7.egg/EGG-INFO/scripts/openmm", line 145, in load_coords
    self.prmtop_file = app.AmberPrmtopFile(self.prmtop)
  File "/home/leeping/.local/lib/python2.7/site-packages/simtk/openmm/app/amberprmtopfile.py", line 75, in __init__
    prmtop = amber_file_parser.PrmtopLoader(file)
  File "/home/leeping/.local/lib/python2.7/site-packages/simtk/openmm/app/internal/amber_file_parser.py", line 127, in __init__
    self._raw_format[self._flags[-1]] = (format, m.group(1), m.group(2), m.group(3), m.group(4))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by peastman** [comment]
This was fixed by #764.
