### ISSUE TITLE
Undefined identifier in Amoeba kernels?

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1016]
```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    context = Context(system, VerletIntegrator(0.002))
  File "/home/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/simtk/openmm/openmm.py", line 4510, in __init__
    this = _openmm.new_Context(*args)
Exception: Error compiling program: (97): error: identifier "INT_MAX" is undefined

(98): error: identifier "INT_MIN" is undefined

(212): error: identifier "INT_MAX" is undefined

3 errors detected in this compilation.
```

```
rmcgibbo@gpu-9-2  ~/projects/openmm/build5 (3.4.2) ‹master*› 
$ cat test.py   
from simtk.openmm import *
from simtk.openmm.app import *

pdb = PDBFile('examples/5dfr_solv-cube_equil.pdb')
ff = ForceField('amoeba2013.xml')
system = ff.createSystem(pdb.topology, nonbondedMethod=PME)
context = Context(system, VerletIntegrator(0.002))
context.setPositions(pdb.positions)
print(context.getPlatform().getName())
print(context.getState(getEnergy=True).getPotentialEnergy())
```

**Comment by rmcgibbo** [comment]
(w/ CUDA 7)
