### ISSUE TITLE
openmm-dev not updated

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1079]
Just a heads-up that `openmm-dev` is having trouble again:
```
+ vagrant ssh --command 'binstar --quiet -t **** upload --force -u omnia --channel main miniconda/conda-bld/linux-64/openmm-dev-*.tar.bz2'
Using binstar api site https://api.anaconda.org
[BinstarError] versions dev already exists 
Traceback (most recent call last):
  File "/home/vagrant/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 187, in main
    add_release(binstar, args, username, package_name, version, release_attrs)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 124, in add_release
    create_release(binstar, username, package_name, version, release_attrs['description'])
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 37, in create_release
    announce, description)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 322, in add_release
    self._check_response(res)
  File "/home/vagrant/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 159, in _check_response
    raise ErrCls(msg, res.status_code)
BinstarError: (u'versions dev already exists', 400)
```
https://jenkins.choderalab.org/job/conda-openmm-dev-linux-vagrant-2/74/console

Will try to resolve tomorrow.

**Comment by jchodera** [comment]
Also `osx`, but with another error message:
```
+ binstar --quiet -t **** upload --force -u omnia miniconda/conda-bld/osx-64/openmm-dev-dev-py27_0.tar.bz2
Using binstar api site https://api.anaconda.org
[warning] Distribution osx-64/openmm-dev-dev-py27_0.tar.bz2 already exists ... removing 
[NotFound] Not Found: Nothing matches the given URI ([DELETE] https://api.anaconda.org/dist/omnia/openmm-dev/dev/osx-64/openmm-dev-dev-py27_0.tar.bz2 -> 404) 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 195, in main
    if remove_existing_file(binstar, args, username, package_name, version, file_attrs):
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 135, in remove_existing_file
    binstar.remove_dist(username, package_name, version, file_attrs['basename'])
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 343, in remove_dist
    self._check_response(res)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 159, in _check_response
    raise ErrCls(msg, res.status_code)
NotFound: (u'Not Found: Nothing matches the given URI ([DELETE] https://api.anaconda.org/dist/omnia/openmm-dev/dev/osx-64/openmm-dev-dev-py27_0.tar.bz2 -> 404)', 404)
```
https://jenkins.choderalab.org/job/conda-openmm-dev-osx-2/74/console

**Comment by jchodera** [comment]
This is now failing because the `python -m simtk.testInstallation` test no longer passes:
```
===== openmm-6.3-py34_0 OK =====
+ python -m simtk.testInstallation
FATAL: Error inserting nvidia (/lib/modules/2.6.32-504.30.3.el6.x86_64/extra/nvidia.ko): No such device
There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Error computing forces with OpenCL platform

OpenCL platform error: Error compiling kernel: "/tmp/OCL8536T77.cl", line 20: warning: OpenCL extension is now part of core
  #pragma OPENCL EXTENSION cl_khr_fp64 : enable
                           ^

"/tmp/OCL8536T77.cl", line 559: error: identifier "CUTOFF" is undefined
              singlePeriodicCopy = (0.5f*periodicBoxSize.x-blockSizeX.x >= CUTOFF &&
                                                                           ^

1 error detected in the compilation of "/tmp/OCL8536T77.cl".

Frontend phase failed compilation.
```
See https://jenkins.choderalab.org/job/conda-openmm-dev-linux-vagrant-2/89/console

**Comment by jchodera** [comment]
There was also another package name issue that prevented the `osx` platform (and the `linux` platform, once this is fixed) packages from being uploaded:
https://github.com/omnia-md/openmm-dev/pull/13

**Comment by rmcgibbo** [comment]
That looks like a legit issue. Do you know what OpenCL device? Could be
related to 8ae2eba

There was also another package name issue that prevented the osx platform
(and the linux platform, once this is fixed) packages from being uploaded:
omnia-md/openmm-dev#13 <https://github.com/omnia-md/openmm-dev/pull/13>

—
Reply to this email directly or view it on GitHub
<https://github.com/pandegroup/openmm/issues/1079#issuecomment-136195383>.

**Comment by jchodera** [comment]
The `linux` builds are currently run on a vagrant VM via VirtualBox on a Mac Mini (Macmini6,2) with Intel HD Graphics 4000 (1 GB VRAM) running OS X 10.9.5.

Oddly enough, the error in `testInstallation.py` doesn't actually cause a failure to be returned, so the build now happily completes and uploads the package.  Should we change that behavior?
```
penCL platform error: Error compiling kernel: "/tmp/OCL18327T77.cl", line 20: warning: OpenCL extension is now part of core
  #pragma OPENCL EXTENSION cl_khr_fp64 : enable
                           ^

"/tmp/OCL18327T77.cl", line 559: error: identifier "CUTOFF" is undefined
              singlePeriodicCopy = (0.5f*periodicBoxSize.x-blockSizeX.x >= CUTOFF &&
                                                                           ^

1 error detected in the compilation of "/tmp/OCL18327T77.cl".

Frontend phase failed compilation.
...
TEST END: openmm-dev-7.0.0.dev0-py34_0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /home/vagrant/miniconda/conda-bld/linux-64/openmm-dev-7.0.0.dev0-py34_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

+ vagrant ssh --command 'binstar --quiet -t **** upload --force -u omnia --channel main miniconda/conda-bld/linux-64/openmm-dev-*.tar.bz2'
Using binstar api site https://api.anaconda.org
+ vagrant halt
```

**Comment by rmcgibbo** [comment]
I have a MacMini5.3, with OSX 10.10, but I guess it only has the CPU OpenCL device, which is skipped.

If you have command line access, modify OpenCLContext.cpp to print the kernel sources on https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLContext.cpp#L578

**Comment by jchodera** [comment]
Thanks!
