### ISSUE TITLE
Deep copy issues: "Exception: the System object does not own its corresponding OpenMM object"

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1102]
I've recently started seeing odd errors like this with Yank tests:
```
[chodera@gpu-3-9 ~]$ python -m doctest github/choderalab/yank/yank.jchodera/Yank/alchemy.py
**********************************************************************
File "github/choderalab/yank/yank.jchodera/Yank/alchemy.py", line 163, in alchemy.AbsoluteAlchemicalFactory
Failed example:
    factory = AbsoluteAlchemicalFactory(reference_system, ligand_atoms=ligand_atoms)
Exception raised:
    Traceback (most recent call last):
      File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest alchemy.AbsoluteAlchemicalFactory[5]>", line 1, in <module>
        factory = AbsoluteAlchemicalFactory(reference_system, ligand_atoms=ligand_atoms)
      File "github/choderalab/yank/yank.jchodera/Yank/alchemy.py", line 223, in __init__
        self.alchemically_modified_system = self._createAlchemicallyModifiedSystem(self.reference_system)
      File "github/choderalab/yank/yank.jchodera/Yank/alchemy.py", line 848, in _createAlchemicallyModifiedSystem
        system.addForce(force)
      File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 9498, in addForce
        raise Exception(s)
    Exception: the System object does not own its corresponding OpenMM object
```
The [lines in question](https://github.com/choderalab/yank/blob/master/Yank/alchemy.py#L847-L848) create a deep copy of a `Force` object and add it to a new `system`:
```
                force = copy.deepcopy(reference_force)
                system.addForce(force)
```
This worked fine before, but seems to now be broken---perhaps after some recent changes to deep copy after #1055?

**Comment by jchodera** [comment]
Minimal test case script is here:
https://gist.github.com/jchodera/6cbc9fb0cef3da717efc
