### ISSUE TITLE
Force group 31 is broken

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1198]
```
import simtk.openmm as mm
system = mm.System()
system.addParticle(1.0)

force = mm.CustomExternalForce('1')
force.addParticle(0, [])
force.setForceGroup(31)
system.addForce(force)

context = mm.Context(system, mm.VerletIntegrator(0))
context.setPositions([(0,0,0)])
context.getState(getEnergy=True, groups=1<<31)
```
```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    context.getState(getEnergy=True, groups=1<<31)
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/simtk/openmm/openmm.py", line 4985, in getState
    self._getStateAsLists(getP, getV, getF, getE, getPa, enforcePeriodic, groups)
  File "/Users/rmcgibbo/miniconda/envs/3.4.2/lib/python3.4/site-packages/simtk/openmm/openmm.py", line 4937, in _getStateAsLists
    return _openmm.Context__getStateAsLists(self, *args)
OverflowError: in method 'Context__getStateAsLists', argument 8 of type 'int'
```

**Comment by rmcgibbo** [comment]
Also if you ask for `context.getState(getEnergy=True, groups=0xFFFFFFFF)`, you also get an overflow error. The C++ signature is declared as `int`, but it really should be `unsigned int`, I think.
