### ISSUE TITLE
Issue with CharmmParameterSet

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1263]
Reported by Jumin to me over email:

There is a compatibility issue in OpenMM 6.3 with Python 3.4.
It seems like that OpenMM generates an error when it tries to determine an element type using the mass:

```
Traceback (most recent call last):
  File "/home/khaos/prog/openmm-6.3/lib/python3.4/site-packages/simtk/openmm/app/charmmparameterset.py", line 522, in readTopologyFile
    elem = words[4]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "openmm_run.py", line 33, in <module>
    params = read_params(inputs.toppar_path)
  File "/panfs/pfs.acf.ku.edu/research/khaos/Test/OpenMM_Error/OpenMM_Python3.4_Error/omm_readparams.py", line 33, in read_params
    params = CharmmParameterSet( *parFiles )
  File "/home/khaos/prog/openmm-6.3/lib/python3.4/site-packages/simtk/openmm/app/charmmparameterset.py", line 137, in __init__
    for top in tops: self.readTopologyFile(top)
  File "/home/khaos/prog/openmm-6.3/lib/python3.4/site-packages/simtk/openmm/app/charmmparameterset.py", line 526, in readTopologyFile
    masselem = Element.getByMass(mass)
  File "/home/khaos/prog/openmm-6.3/lib/python3.4/site-packages/simtk/openmm/app/element.py", line 126, in getByMass
    Element._elements_by_mass[elem.mass] = elem
  File "/tools/cluster/6.2/python/3.4.2/lib/python3.4/collections/__init__.py", line 63, in __setitem__
    if key not in self:
TypeError: unhashable type: 'Quantity'
```

FYI, I do not see this error with Python 2.7.
Could you please have a look at this?

The test case is downloadable using the following link:
https://www.dropbox.com/s/rozisiby61uum85/OpenMM_Python3.4_Error.tar?dl=0

This is just a reminder for me to look into it and a reference for others that it exists. (This is with OpenMM 6.3 -- I'm not 100% sure that the problem still exists).

**Comment by swails** [comment]
I can repro this bug in 6.3 but it runs fine in master.  I'm having a hard time figuring out exactly what change fixed this, but I do vaguely remember fixing what was likely this exact problem.

Closing since it's already fixed, and there's nothing we can do about it in OpenMM 6.3.  I'll open an issue on the official issue tracker so we can mark it as fixed for 7.0.
