### ISSUE TITLE
loadCheckpoint doesn't set the flag that coordinates are read

### ISSUE THREAD

**Issue by sinitskiy** [pandegroup/openmm#1284]
When I tried to load a cpr file and restart a simulation by including into a python script the following:
```
with open('file_written_by_CheckpointReporter_at_the_end_of_previous_simulation.cpr', 'rb') as f:
    simulation.context.loadCheckpoint(f.read())
```
I got an error message:
```
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    simulation.step(24000000)
  File "/home/sinitsk/.local/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 95, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/sinitsk/.local/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 148, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/sinitsk/.local/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 1482, in step
    return _openmm.LangevinIntegrator_step(self, *args)
Exception: Particle positions have not been set
```
This error doesn't appear with a py script that contains:
```
simulation.context.setPositions([mm.Vec3(0,0,0)]*system.getNumParticles())
with open('file_written_by_CheckpointReporter_at_the_end_of_previous_simulation.cpr', 'rb') as f:
    simulation.context.loadCheckpoint(f.read())
```
It would be more convenient and less error-prone if one wouldn't have to create or load wrong coordinates before loading a checkpoint file with the right coordinates.

**Comment by rmcgibbo** [comment]
(@sinitskiy: I edited the issue to put the code segments inside triple backtics so that it gets rendered as monospaced)
