### ISSUE TITLE
pdbstructure.py ValueError

### ISSUE THREAD

**Issue by cxhernandez** [pandegroup/openmm#1318]
I've added a `PDBReporter` to my `simulation` object

```python
simulation.reporters.append(
    PDBReporter('./RUN%d/equil.pdb' % options.run, options.n_steps/options.n_clones))
```

and then try to read this `PDB` (w/ 5 frames) later in my script

```python
seeds = PDBFile('./RUN%d/equil.pdb' % options.run)
```

but this results in the following `ValueError` using OpenMM 6.3 on the new Xstream cluster:

```
Traceback (most recent call last):
  File "./equil.py", line 45, in <module>
    seeds = PDBFile('./RUN%s/equil.pdb' % options.run)
  File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/OpenMM/6.3/python-wrappers/lib/simtk/openmm/app/pdbfile.py", line 82, in __init__
    pdb = PdbStructure(inputfile, load_all_models=True)
  File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/OpenMM/6.3/python-wrappers/lib/simtk/openmm/app/internal/pdbstructure.py", line 146, in __init__
    self._load(input_stream)
  File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/OpenMM/6.3/python-wrappers/lib/simtk/openmm/app/internal/pdbstructure.py", line 157, in _load
    self._add_atom(Atom(pdb_line, self))
  File "/global/software/MPI/GCC/4.9.2/OpenMPI/1.8.5/OpenMM/6.3/python-wrappers/lib/simtk/openmm/app/internal/pdbstructure.py", line 772, in __init__
    y = float(pdb_line[38:46])
ValueError: could not convert string to float:
```

I am able to successfully load the same `PDB` using MDTraj, however:

```python
In [1]: import mdtraj as md
In [2]: pdb = md.load('equil.pdb')
In [3]: pdb
Out[3]: <mdtraj.Trajectory with 5 frames, 62464 atoms, 19565 residues, and unitcells at 0x7fb8fe260278>
```

**Comment by jchodera** [comment]
Can you post an excerpt from one of the affected pdbs?

**Comment by cxhernandez** [comment]
Here are the first 50 lines:

```
REMARK   1 CREATED WITH OPENMM 6.3, 2016-01-04
CRYST1   87.262   87.262   87.262  90.00  90.00  90.00 P 1           1
MODEL        1
ATOM      1  N   PHE A   1      12.692  41.704 -24.790  1.00  0.00           N
ATOM      2  H   PHE A   1      13.005  41.616 -25.746  1.00  0.00           H
ATOM      3  H2  PHE A   1      13.476  42.033 -24.245  1.00  0.00           H
ATOM      4  H3  PHE A   1      12.456  40.766 -24.499  1.00  0.00           H
ATOM      5  CA  PHE A   1      11.544  42.655 -24.689  1.00  0.00           C
ATOM      6  HA  PHE A   1      10.716  42.194 -25.227  1.00  0.00           H
ATOM      7  CB  PHE A   1      11.092  42.824 -23.229  1.00  0.00           C
ATOM      8  HB2 PHE A   1      10.206  43.459 -23.252  1.00  0.00           H
ATOM      9  HB3 PHE A   1      11.925  43.287 -22.701  1.00  0.00           H
ATOM     10  CG  PHE A   1      10.723  41.517 -22.506  1.00  0.00           C
ATOM     11  CD1 PHE A   1       9.943  40.556 -23.136  1.00  0.00           C
ATOM     12  HD1 PHE A   1       9.528  40.713 -24.121  1.00  0.00           H
ATOM     13  CD2 PHE A   1      11.185  41.290 -21.195  1.00  0.00           C
ATOM     14  HD2 PHE A   1      11.777  42.054 -20.713  1.00  0.00           H
ATOM     15  CE1 PHE A   1       9.683  39.356 -22.487  1.00  0.00           C
ATOM     16  HE1 PHE A   1       9.066  38.624 -22.986  1.00  0.00           H
ATOM     17  CE2 PHE A   1      10.890  40.076 -20.542  1.00  0.00           C
ATOM     18  HE2 PHE A   1      11.245  39.873 -19.542  1.00  0.00           H
ATOM     19  CZ  PHE A   1      10.144  39.105 -21.200  1.00  0.00           C
ATOM     20  HZ  PHE A   1       9.907  38.150 -20.756  1.00  0.00           H
ATOM     21  C   PHE A   1      11.939  43.994 -25.331  1.00  0.00           C
ATOM     22  O   PHE A   1      13.033  44.443 -25.129  1.00  0.00           O
ATOM     23  N   GLU A   2      11.019  44.622 -26.065  1.00  0.00           N
ATOM     24  H   GLU A   2      10.066  44.296 -26.133  1.00  0.00           H
ATOM     25  CA  GLU A   2      11.313  45.873 -26.799  1.00  0.00           C
ATOM     26  HA  GLU A   2      12.319  45.767 -27.205  1.00  0.00           H
ATOM     27  CB  GLU A   2      10.374  45.985 -28.041  1.00  0.00           C
ATOM     28  HB2 GLU A   2      10.446  45.059 -28.612  1.00  0.00           H
ATOM     29  HB3 GLU A   2      10.752  46.827 -28.620  1.00  0.00           H
ATOM     30  CG  GLU A   2       8.915  46.229 -27.671  1.00  0.00           C
ATOM     31  HG2 GLU A   2       8.565  45.457 -26.986  1.00  0.00           H
ATOM     32  HG3 GLU A   2       8.815  47.188 -27.163  1.00  0.00           H
ATOM     33  CD  GLU A   2       7.964  46.161 -28.860  1.00  0.00           C
ATOM     34  OE1 GLU A   2       7.236  47.171 -29.092  1.00  0.00           O
ATOM     35  OE2 GLU A   2       7.855  45.126 -29.547  1.00  0.00           O
ATOM     36  C   GLU A   2      11.242  47.103 -25.886  1.00  0.00           C
ATOM     37  O   GLU A   2      10.415  47.174 -24.996  1.00  0.00           O
ATOM     38  N   ARG A   3      12.122  48.107 -26.121  1.00  0.00           N
ATOM     39  H   ARG A   3      12.787  48.006 -26.874  1.00  0.00           H
ATOM     40  CA  ARG A   3      12.171  49.349 -25.290  1.00  0.00           C
ATOM     41  HA  ARG A   3      11.929  49.096 -24.258  1.00  0.00           H
ATOM     42  CB  ARG A   3      13.623  49.939 -25.351  1.00  0.00           C
ATOM     43  HB2 ARG A   3      13.784  50.387 -26.331  1.00  0.00           H
ATOM     44  HB3 ARG A   3      14.333  49.119 -25.244  1.00  0.00           H
ATOM     45  CG  ARG A   3      13.868  50.950 -24.228  1.00  0.00           C
ATOM     46  HG2 ARG A   3      13.022  51.618 -24.071  1.00  0.00           H
ATOM     47  HG3 ARG A   3      14.050  50.386 -23.313  1.00  0.00           H
```

**Comment by rmcgibbo** [comment]
IIRC, the mdtraj and openmm code are almost identical. The best thing to have though would be the whole line (`pdb_line` in the traceback) of the file at which it fails.

**Comment by peastman** [comment]
Can you provide the complete file?  That way I can try to reproduce the problem.

**Comment by cxhernandez** [comment]
I think I found the issue. The last line of the PDB file seems incomplete:

```
$ tail equil.pdb
ATOM  60826  H1  HOH B8721      35.346  10.515  35.456  1.00  0.00           H
ATOM  60827  H2  HOH B8721      35.564  11.676  36.402  1.00  0.00           H
ATOM  60828  O   HOH B8722      42.775  80.942  23.496  1.00  0.00           O
ATOM  60829  H1  HOH B8722      43.3
```

until the script terminates:

```
$ tail equil.pdb
ATOM  62459  H2  HOH B9265      57.242  23.633  38.206  1.00  0.00           H
ATOM  62460  O   HOH B9266      35.243  10.224  39.874  1.00  0.00           O
ATOM  62461  H1  HOH B9266      35.832  10.063  39.137  1.00  0.00           H
ATOM  62462  H2  HOH B9266      34.714  10.972  39.599  1.00  0.00           H
ATOM  62463  O   HOH B9267      39.890  13.372  35.854  1.00  0.00           O
ATOM  62464  H1  HOH B9267      40.687  13.424  36.383  1.00  0.00           H
ATOM  62465  H2  HOH B9267      40.011  12.592  35.314  1.00  0.00           H
TER   62466      HOH B9267
ENDMDL
END
```

Is there a way to close the `Simulation` object, so that `PDBReporter` finishes writing to the file?

**Comment by jchodera** [comment]
What about also adding a call to the reporter to flush/sync to disk?

**Comment by rmcgibbo** [comment]
I thought `PDBReporter` already flushed after each report. https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/pdbreporter.py#L94-L95

**Comment by peastman** [comment]
How about `del simulation`?

Flushing the stream isn't enough.  A PDB file has a footer with important information (CONECT records) that needs to come after all models, so it doesn't get written until the PDBReporter is deleted.

**Comment by rmcgibbo** [comment]
But doesn't the first `tail` output https://github.com/pandegroup/openmm/issues/1318#issuecomment-168781240 show that the last line was half-written, not just the footer?

**Comment by cxhernandez** [comment]
`del simulation` didn't work, but adding a call to `pdbreporter._out.flush()` did

**Comment by mpharrigan** [comment]
The call to flush was added recently https://github.com/pandegroup/openmm/commit/22fc6e88490b77946252430bfbdf8de9e9563763#diff-bfc95f19cd0e66f2eec4998f018eb1c7

**Comment by cxhernandez** [comment]
ahah! thanks @mpharrigan!
