### ISSUE TITLE
Double-precision OpenCL support broken for OS X 10.10.5?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1379]
I have an iMac Retina 5K running OS X 10.10.5, and have just discovered that using `double` precision on OpenCL doesn't seem to work:
```
======================================================================
ERROR: Testing alchemical null elimination for 'ethane' with 50 NCMC steps
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/tests/test_elimination.py", line 112, in check_alchemical_null_elimination
    [positions, logP_delete, potential_delete] = ncmc_engine.integrate(topology_proposal, positions, direction='delete')
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/annihilation/ncmc_switching.py", line 262, in integrate
    context = openmm.Context(alchemical_system, integrator, self.platform)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 6250, in __init__
    this = _openmm.new_Context(*args)
Exception: Error compiling kernel: <program source>:59:6: warning: no previous prototype for function 'writeForces'
void writeForces(__global real4* forceBuffers,__local AtomData* localData, int atomIndex) {
     ^
<program source>:69:27: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned int')
            isFirst &= (i >= get_local_id(0));
                        ~ ^  ~~~~~~~~~~~~~~~
<program source>:168:16: error: call to '__cl_pow' is ambiguous
float temp21 = pow(temp20, 1.6666666666666666e-01);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4662:27: note: expanded from macro 'pow'
    #define pow(__x, __y) __cl_pow(__x, __y)
                          ^~~~~~~~
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4659:15: note: candidate function
__CLFN_FD_2FD(__cl_pow);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:996:48: note: expanded from macro '__CLFN_FD_2FD'
#define __CLFN_FD_2FD(name) float __OVERLOAD__ name(float x, float y); \
                                               ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4659:15: note: candidate function
__CLFN_FD_2FD(__cl_pow);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:1002:21: note: expanded from macro '__CLFN_FD_2FD'
double __OVERLOAD__ name(double x, double y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4659:15: note: candidate function
__CLFN_FD_2FD(__cl_pow);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:997:21: note: expanded from macro '__CLFN_FD_2FD'
float2 __OVERLOAD__ name(float2 x, float2 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4659:15: note: candidate function
__CLFN_FD_2FD(__cl_pow);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:998:21: note: expanded from macro '__CLFN_FD_2FD'
float3 __OVERLOAD__ name(float3 x, float3 y); \
                    ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:4659:15: note: candidate function
__CLFN_FD_2FD(__cl_pow);
              ^
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/3.2/include/cl_kernel.h:999:21: note: expanded from macro '__CLFN_FD_2FD'
float4 __OVERLOAD__ name(float4 x, float4 y); \
                    ^
```
What's even weirder is that standard `mixed` precision gives really, really weird statistics.  The forces and energies don't seem to be *too* discrepant, but doing some nonequilibrium stat mech with `CustomIntegrator` gives crazy numbers.  Surprisingly, both `CPU` (which is also single-precision) and `Reference` (double precision) don't have trouble.

I'm trying to figure out if I can come up with a minimal test case for the odd default behavior, but I'm having a hard time doing so since I suspect it might be some odd numerical issues within `CustomIntegrator`.

**Comment by rmcgibbo** [comment]
If you can print the build kernel sources, that usually helps: https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLContext.cpp#L582

**Comment by jchodera** [comment]
What if we add an `OpenCL` platform property that turns that on?

**Comment by jchodera** [comment]
Actually, it looks like this isn't working on `linux` either when `OpenCL` is used in `double` precision.

Will try to assemble minimal test case, but the `CustomIntegrator` code is [here](https://github.com/choderalab/perses/blob/master/perses/annihilation/ncmc_switching.py#L359-L498).

**Comment by jchodera** [comment]
Here's the trace from the `linux` failure:
```
======================================================================
ERROR: Compare NCMC integrator behavior across platforms.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/cbio/jclab/home/chodera/github/choderalab/perses/perses.choderalab/perses/tests/test_elimination.py", line 262, in test_ncmc_integrator_platforms
    context = openmm.Context(alchemical_system, ncmc_integrator, platform)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 13878, in __init__
    this = _openmm.new_Context(*args)
Exception: Error compiling kernel: <kernel>:168:16: error: call to 'pow' is ambiguous
float temp21 = pow(temp20, 1.6666666666666666e-01);
               ^~~
cl_kernel.h:1900:25: note: candidate function
double __OVERLOADABLE__ pow(double, double);
                        ^
cl_kernel.h:6096:24: note: candidate function
float __OVERLOADABLE__ pow(float, float);
                       ^
cl_kernel.h:1901:25: note: candidate function
float2 __OVERLOADABLE__ pow(float2, float2); 
                        ^
cl_kernel.h:1903:25: note: candidate function
float3 __OVERLOADABLE__ pow(float3, float3); 
                        ^
cl_kernel.h:1905:25: note: candidate function
float4 __OVERLOADABLE__ pow(float4, float4); 
                        ^
cl_kernel.h:1906:25: note: candidate function
float8 __OVERLOADABLE__ pow(float8, float8); 
                        ^
cl_kernel.h:1907:26: note: candidate function
float16 __OVERLOADABLE__ pow(float16, float16); 
                         ^
cl_kernel.h:1908:26: note: candidate function
double2 __OVERLOADABLE__ pow(double2, double2); 
                         ^
cl_kernel.h:1910:26: note: candidate function
double3 __OVERLOADABLE__ pow(double3, double3); 
                         ^
cl_kernel.h:1912:26: note: candidate function
double4 __OVERLOADABLE__ pow(double4, double4); 
                         ^
cl_kernel.h:1913:26: note: candidate function
double8 __OVERLOADABLE__ pow(double8, double8); 
                         ^
cl_kernel.h:1914:27: note: candidate function
double16 __OVERLOADABLE__ pow(double16, double16); 
                          ^
<kernel>:187:16: error: call to 'pow' is ambiguous
float temp30 = pow(temp20, -8.3333333333333337e-01);
...
```

**Comment by peastman** [comment]
In double precision mode, the "temp" variables should all be double, not float.  I'm investigating now.
