### ISSUE TITLE
Does CPU platform implement 'single' or 'mixed' precision?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1626]
The `CPU` platform doesn't support the `mixed` precision choice, but I was under the impression it used `mixed` (rather than `single`):
```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/yank-0.11.1-py2.7-linux-x86_64.egg/yank/tests/test_yaml.py", line 1497, in test_select_fastest_platform
    yaml_builder._configure_platform(platform_precision='single')
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/yank-0.11.1-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 2132, in _configure_platform
    "only 'mixed' is supported.".format(platform_precision))
RuntimeError: CPU platform does not support precision model 'single';only 'mixed' is supported.
```

**Comment by jchodera** [comment]
Whoops, this is an issue on our side.
