### ISSUE TITLE
re.sub() Python 2.7-ism in swigInputBuilder.py breaking compatibility with Python 2.6 during build

### ISSUE THREAD

**Issue by mjw99** [pandegroup/openmm#1656]
Seeing this with 5e86c4f76c on the following machine: [login-sand1.hpc.cam.ac.uk](http://www.hpc.cam.ac.uk/services/wilkes)
  
```
[mw529@login-sand1 openmm-7.0.1-build]$ cat /etc/redhat-release
Scientific Linux release 6.8 (Carbon)
```
Using the following build protocol:
```
module purge
module add cuda/8.0
module add swig/3.0.8

wget https://github.com/pandegroup/openmm/archive/7.0.1.tar.gz -O openmm-7.0.1.tar.gz
tar xf openmm-7.0.1.tar.gz
mkdir openmm-7.0.1-build && cd openmm-7.0.1-build
cmake ../openmm-7.0.1/
make

....<snip>...
Generate XML output for dir /home/mw529/workspace/openmm-7.0.1/serialization/
[ 98%] Creating OpenMM Python swig input files...
Traceback (most recent call last):
  File "/home/mw529/workspace/openmm-7.0.1-build/python/src/swig_doxygen/swigInputBuilder.py", line 719, in <module>
    main()
  File "/home/mw529/workspace/openmm-7.0.1-build/python/src/swig_doxygen/swigInputBuilder.py", line 693, in main
    sBuilder.writeSwigFile()
  File "/home/mw529/workspace/openmm-7.0.1-build/python/src/swig_doxygen/swigInputBuilder.py", line 654, in writeSwigFile
    self.writeClassDeclarations()
  File "/home/mw529/workspace/openmm-7.0.1-build/python/src/swig_doxygen/swigInputBuilder.py", line 338, in writeClassDeclarations
    docstring = striphtmltags(docstring)
  File "/home/mw529/workspace/openmm-7.0.1-build/python/src/swig_doxygen/swigInputBuilder.py", line 52, in striphtmltags
    s = re.sub('\s*(<ul>.*?</ul>\s*)', replace_ul_tags, s, flags=re.MULTILINE | re.DOTALL)
TypeError: sub() got an unexpected keyword argument 'flags'
make[2]: *** [python/src/swig_doxygen/swig_lib/python/pythonprepend.i] Error 1
make[1]: *** [wrappers/python/CMakeFiles/BuildModule.dir/all] Error 2
make: *** [all] Error 2
```

It looks like the flags argument to re.sub() was added in Python 2.7 and the system default is Python 2.6. I think the commit that changed this was here: 04f68ba4

I'm not sure whether to fix that or state that Python 2.7 is required instead of 2.6.

**Comment by peastman** [comment]
I'd be fine with just moving the minimum requirement to 2.7.  If anyone is still using 2.6, they really ought to upgrade.

**Comment by mjw99** [comment]
Sounds fine with here; there is Python 2.7 support on that cluster via the module command.

**Comment by mpharrigan** [comment]
semi-relevant http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Comment by mjw99** [comment]
Given [this,](https://github.com/pandegroup/openmm/issues/1613#issuecomment-252100869) I think this can probably be closed now.
