### ISSUE TITLE
Deep copying TabulatedFunction objects in CustomGBForce

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1707]
I'm adding support for alchemically-modified `CustomGBForce`-encoded GBSA models to YANK in [this PR](https://github.com/choderalab/alchemy/blob/40d634db3a9c3b6a8b9d26528d041faf59c7e9d0/alchemy/alchemy.py#L1425-L1521). This is a straightforward exercise in simply rewriting some of the computation expressions using some substitution rules, but I'm running into problems copying over `TabulatedFunction` objects used in certain `CustomGBForce`-encoded GBSA models.

If I simply retrieve the `TabulatedFunction` with `reference_force.getTabulatedFunction(index)` and try adding it to a new `CustomGBForce`, I get the exception:
```
Exception: the CustomGBForce object does not own its corresponding OpenMM object
```
If I try to `copy.deepcopy` the `TabulatedFunction`, I get a `swig` error:
```
======================================================================
ERROR: Test that alchemical modification of GBSA parameters correctly recovers fully-interacting and noninteracting parameters.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/alchemy/alchemy.choderalab/alchemy/tests/test_alchemy.py", line 1453, in test_gbsa_models
    factory = AbsoluteAlchemicalFactory(reference_system, **factory_args)
  File "/Users/choderaj/github/choderalab/alchemy/alchemy.choderalab/alchemy/alchemy.py", line 365, in __init__
    [self.alchemically_modified_system, self.force_labels] = self._createAlchemicallyModifiedSystem(self.reference_system)
  File "/Users/choderaj/github/choderalab/alchemy/alchemy.choderalab/alchemy/alchemy.py", line 1586, in _createAlchemicallyModifiedSystem
    self._alchemicallyModifyCustomGBForce(system, reference_force, force_labels)
  File "/Users/choderaj/github/choderalab/alchemy/alchemy.choderalab/alchemy/alchemy.py", line 1516, in _alchemicallyModifyCustomGBForce
    function_copy = copy.deepcopy(function)
  File "/Users/choderaj/miniconda/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/Users/choderaj/miniconda/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/choderaj/miniconda/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/Users/choderaj/miniconda/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/choderaj/miniconda/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: can't pickle SwigPyObject objects
```
There doesn't appear to be any sort of [documented public interface](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.TabulatedFunction.html#simtk.openmm.openmm.TabulatedFunction) for creating a new `TabulatedFunction` by accessing the contents of an existing one.

Any ideas?

**Comment by jchodera** [comment]
I just noticed that `TabulatedFunction` and its subclasses have a [`Copy()` member function](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.TabulatedFunction.html#simtk.openmm.openmm.TabulatedFunction.Copy), but using this [to add a copy of the `TabulatedFunction` to the new `CustomGBForce`](https://github.com/choderalab/alchemy/blob/b92548ce0c3c3486cde952fabf609acb3621314b/alchemy/alchemy.py#L1512-L1517) also results in an error that `CustomGBForce` does not own its corresponding OpenMM object:
```
======================================================================
ERROR: Test that alchemical modification of GBSA parameters correctly recovers fully-interacting and noninteracting parameters.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/alchemy/alchemy.choderalab/alchemy/tests/test_alchemy.py", line 1453, in test_gbsa_models
    factory = AbsoluteAlchemicalFactory(reference_system, **factory_args)
  File "/Users/choderaj/github/choderalab/alchemy/alchemy.choderalab/alchemy/alchemy.py", line 365, in __init__
    [self.alchemically_modified_system, self.force_labels] = self._createAlchemicallyModifiedSystem(self.reference_system)
  File "/Users/choderaj/github/choderalab/alchemy/alchemy.choderalab/alchemy/alchemy.py", line 1586, in _createAlchemicallyModifiedSystem
    self._alchemicallyModifyCustomGBForce(system, reference_force, force_labels)
  File "/Users/choderaj/github/choderalab/alchemy/alchemy.choderalab/alchemy/alchemy.py", line 1517, in _alchemicallyModifyCustomGBForce
    custom_force.addTabulatedFunction(name, function_copy)
  File "/Users/choderaj/miniconda/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 9487, in addTabulatedFunction
    raise Exception(s)
Exception: the CustomGBForce object does not own its corresponding OpenMM object
```
The [copy idiom](https://github.com/choderalab/alchemy/blob/b92548ce0c3c3486cde952fabf609acb3621314b/alchemy/alchemy.py#L1512-L1517) I used is:
```python
        # Add tabulated functions
        for function_index in range(reference_force.getNumTabulatedFunctions()):
            name = reference_force.getTabulatedFunctionName(function_index)
            function = reference_force.getTabulatedFunction(function_index)
            function_copy = function.Copy()
            custom_force.addTabulatedFunction(name, function_copy)
```

**Comment by peastman** [comment]
I didn't even know those `Copy()` methods were there.  It looks like they were added just to support a copy constructor for `CustomNonbondedForce`.  But that could be handled much more simply with `XmlSerializer::clone()`.  Anyone object if I mark them as deprecated, to be removed in a later release?

**Comment by jchodera** [comment]
> But that could be handled much more simply with XmlSerializer::clone()

Can you clarify how that would work at the Python level? Or would this be a C++ change that would then provide proper support for `copy.deepcopy()`?

**Comment by peastman** [comment]
Completely separate.  I'm also adding support for `deepcopy()` in Python, but that's done at the SWIG level.
