### ISSUE TITLE
OpenMM 7.0 crashes with large system (500k atoms)

### ISSUE THREAD

**Issue by JoaoRodrigues** [pandegroup/openmm#1742]
Hi all,

I'm trying to setup a simulation of a fairly large system (~500.000 atoms) using OpenMM 7.0, compiled against CUDA 8.0.4 and GCC 4.9.2. The script I'm using, which works fine for a small system (14.000 atoms), is [here](https://github.com/csblab/md_scripts/blob/master/openmm/minimize.py), fairly vanilla. It builds a rhombic dodecahedron box, solvates it, minimizes energy, and proceeds to do NVT equilibration.

Adding hydrogens, solvent, etc, works well. Minimization gives problems however. It seems the minimizer cannot handle such a large system and so, as soon as NVT MD starts, the simulation crashes. Running this without position restraints doesn't make a difference. See my log below:

```
[2017/02/16 00:10:06] Using platform: CUDA
[2017/02/16 00:10:06] Reading PDB file: model.pdb
[2017/02/16 00:10:13] Adding missing atoms
[2017/02/16 00:25:26] Moving system to origin
[2017/02/16 00:25:31] Calculating optimal box size
[2017/02/16 00:25:56] System      : 131218 Atoms   8452 Residues
[2017/02/16 00:25:56] System Size : 17.227 17.026 16.138
[2017/02/16 00:25:56] Diameter    : 18.673
[2017/02/16 00:25:56] Box Volume  : 5891.645
[2017/02/16 00:25:56] Box Vectors :
[2017/02/16 00:25:56]   u = 20.273  0.000  0.000
[2017/02/16 00:25:56]   v =  0.000 20.273  0.000
[2017/02/16 00:25:56]   w = 10.136 10.136 14.335
[2017/02/16 00:25:56] Solvating the system
[2017/02/16 00:27:43]   num. waters: 140648
[2017/02/16 00:27:43]   num. ions:    507 Na    383 Cl
[2017/02/16 00:28:29] Adding pos. res. on non-hydrogen protein atoms
[2017/02/16 00:28:32] 64606/554052 atoms restrained (Fc=  10.000 kJ/mol.nm^2)
[2017/02/16 00:28:43] Initial Potential Energy: 1084443494602997235712.000
[2017/02/16 00:28:57] Running energy minimization
[2017/02/16 00:29:53] Potential Energy after minimization: 1070829797063901315072.000
[2017/02/16 00:30:06] Releasing restraints on protein heavy atoms
[2017/02/16 00:30:06] Equilibrating system at 300K for 0.5 ns
#"Step"	"Potential Energy (kJ/mole)"	"Kinetic Energy (kJ/mole)"	"Total Energy (kJ/mole)"	"Temperature (K)"	"Speed (ns/day)"
Traceback (most recent call last):
  File "minimize.py", line 240, in <module>
    simulation.step(n_of_steps)
  File "/home/stanford/levittm/shared/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/stanford/levittm/shared/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 219, in _simulate
    reporter.report(self, state)
  File "/home/stanford/levittm/shared/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/statedatareporter.py", line 195, in report
    self._checkForErrors(simulation, state)
  File "/home/stanford/levittm/shared/software/miniconda2/lib/python2.7/site-packages/simtk/openmm/app/statedatareporter.py", line 347, in _checkForErrors
    raise ValueError('Energy is NaN')
ValueError: Energy is NaN
```

Reading the issue tracker, it seems there is a [known problem with the TIP3P water model](https://github.com/pandegroup/openmm/issues/719#issuecomment-62794408) (issue #719). Is there any workaround you recommend? I can minimize the system in GROMACS (works well) and pass the optimized coordinates to OpenMM, but it sort of defeats the purpose of switching to OpenMM :) I could also switch to CHARMM and use their TIP3SP water model, which adds LJ terms to the hydrogens.

Thanks!

João

**Comment by JoaoRodrigues** [comment]
Small update. Generating a system with GROMACS (using CHARMM36) works wonders. Curiously, the initial energy is much much lower. I did not do any minimization in GROMACS, so this might just mean their protocol for water placement is better?

```[2017/02/16 04:04:14] Using platform: CUDA
[2017/02/16 04:04:14] Reading GRO file: model_box.gro
[2017/02/16 04:04:33] Reading TOP file: model.top
[2017/02/16 04:04:54] Reading FF definitions from /home/stanford/levittm/shared/software/gromacs/share/gromacs/top
[2017/02/16 04:04:54] Building system objects
[2017/02/16 04:05:58] System: 685328 Atoms 194062 Residues
[2017/02/16 04:05:58]         num. waters: 184250
[2017/02/16 04:05:58]         num. ions:    742 Na    618 Cl
[2017/02/16 04:06:12] Initial Potential Energy: -3862460.553
[2017/02/16 04:06:12] Running energy minimization in vacuum
[2017/02/16 04:16:26] Potential Energy after minimization: -10955186.080
[2017/02/16 04:16:26] Equilibrating system at 300K for 0.5 ns
#"Step"	"Potential Energy (kJ/mole)"	"Kinetic Energy (kJ/mole)"	"Total Energy (kJ/mole)"	"Temperature (K)"	"Speed (ns/day)"
100	-10632072.5992	327682.389352	-10304390.2098	54.8664412336	0
200	-10364064.1052	594101.872774	-9769962.23244	99.4751520023	2.17
300	-10141628.8211	809370.939548	-9332257.88152	135.51934597	2.17
400	-9958865.3884	985215.567639	-8973649.82076	164.962395908	2.14
500	-9802786.94637	1125890.29587	-8676896.65051	188.516672732	2.11
600	-9668903.60499	1236391.58149	-8432512.0235	207.018772603	2.1
700	-9555241.082	1327090.9154	-8228150.1666	222.205275863	2.09
800	-9456444.44903	1402137.93144	-8054306.51759	234.77098836	2.08
900	-9370949.327	1461254.10002	-7909695.22698	244.669273697	2.07
1000	-9296671.97901	1511450.89076	-7785221.08825	253.074117408	2.06
1100	-9232084.08338	1551227.99718	-7680856.08621	259.734311372	2.05
1200	-9175220.11116	1586747.29176	-7588472.8194	265.681586391	2.05
1300	-9123022.62692	1615571.70337	-7507450.92355	270.507884469	2.03
1400	-9080361.16938	1639099.11068	-7441262.0587	274.447263431	2.03
1500	-9040850.05837	1659180.04053	-7381670.01784	277.809571548	2.03
1600	-9008901.61749	1674373.00914	-7334528.60835	280.353449847	2.02
1700	-8976745.29277	1688176.43743	-7288568.85534	282.664666475	2.01
1800	-8955398.95472	1702342.83087	-7253056.12385	285.036657215	2
1900	-8932892.24037	1712511.88696	-7220380.35342	286.739342304	2
2000	-8913114.90827	1724535.60365	-7188579.30462	288.752567813	2
2100	-8899358.05754	1737793.75948	-7161564.29807	290.972485183	2
...
```

**Comment by msultan** [comment]
Personally, I have sometimes found that minimizing on the CUDA platform lead to weird NaN issues too. Using the CPU platform to minimize and switching to GPU for production runs seems to fix them always.

**Comment by JoaoRodrigues** [comment]
Thanks @msultan but given the unreal energy reporter *before* minimization, I think this might be a placement issue. I'll run the same setup with GROMACS and AMBER/TIP3P to see if I get such a large energy. I'll also try running the minimization on the CPU, but with such a large system it might take a while!

**Comment by peastman** [comment]
> [2017/02/16 00:28:43] Initial Potential Energy: 1084443494602997235712.000

That line is a pretty clear indication that your initial conformation has serious clashes.  If the initial forces and energies are too absurd, the minimizer can't really do anything about it.

**Comment by JoaoRodrigues** [comment]
@peastman Yes. It does have clashes. In the solvent. GROMACS' `solvate` will not give me a box with such problems, so I think the problem might be in the `addSolvent` method of OpenMM. I'll check this a bit better and let you know. For now, using GMX works, the simulations are running.

**Comment by JoaoRodrigues** [comment]
Just to confirm: this is forcefield independent. Ran `gmx solvate` with AMBER99sb-ILDN on the same structure and I get a good initial potential energy (`Epot = -3704958.054`). The problem comes from the water placement in `modeller.addSolvent`.

On a smaller system, OpenMM places roughly 60 more waters on a similarly sized box. I will try to reproduce these numbers on boxes of exactly the same size, but my guess is that the cutoffs used by `addSolvent` might be too short and there are waters placed too close to the solute.

**Comment by peastman** [comment]
Could you post the files needed to reproduce this?  I'd like to figure out why it's creating a clash.

**Comment by JoaoRodrigues** [comment]
@peastman sorry, forgot about this..

The Python script I am using is [here](https://github.com/csblab/md_scripts/blob/master/openmm/minimize.py). I put the initial PDB file in a gist [here](https://gist.github.com/JoaoRodrigues/c1ece4b1d1bd1c32cecf997e2e0f2f67).

**Comment by peastman** [comment]
The script is running out of memory:

```
Traceback (most recent call last):
  File "minimize.py", line 125, in <module>
    xyz_diam = pw_dist(xyz)
  File "minimize.py", line 34, in pw_dist
    return np.amax(pdist(xyz_array, 'euclidean'))
  File "/home/peastman/miniconda3/lib/python3.5/site-packages/scipy/spatial/distance.py", line 1220, in pdist
    dm = np.zeros((m * (m - 1)) // 2, dtype=np.double)
MemoryError
```

There's no need to recompute the box vectors every time, since it looks like that's an expensive computation.  Can you just post the values being used for the box vectors?  Print them out to 18 decimal places to be sure there's no roundoff error.

**Comment by JoaoRodrigues** [comment]
Indeed. That's why I wrote the Cythonized code. 

Box Vectors (up to 18 decimals):
```
u = 20.711255142293371279 0.000000000000000000 0.000000000000000000
 v = 0.000000000000000000 20.711255142293371279 0.000000000000000000
w = 10.355627571146685639 10.355627571146685639 14.645068958000397430
```

**Comment by peastman** [comment]
I just posted a PR with the fix.  The error happened when adding solvent to a system with a triclinic box, and when the initial (non-solvated) system spanned multiple boxes.  It would sometimes cause water to be put in places that produced severe clashes.

**Comment by JoaoRodrigues** [comment]
Thanks @peastman !
