### ISSUE TITLE
OpenMM example script for DualAMDIntegrator

### ISSUE THREAD

**Issue by leelasd** [pandegroup/openmm#1862]
Hi,

I have been trying to figure out how to use AMDForceGroupIntegrator in OpenMM. I have been getting the below error. 

Do I need to combine AMDForceGroupIntegrator with Langevin Integrator to reproduce simulations from [http://dx.doi.org/10.1021/ct400514p](Accelerated Molecular Dynamics Simulations with the AMOEBA Polarizable Force Field on Graphics Processing Units) paper ? 
 
```
Traceback (most recent call last):
  File "OpenMM_PureLiquids_fromCHARMMformat.py", line 80, in <module>
    sim.step(100000)
  File "/home/fas/jorgensen/lsd9/CINF-COMP/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/fas/jorgensen/lsd9/CINF-COMP/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 194, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/home/fas/jorgensen/lsd9/CINF-COMP/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 8200, in step
    return _openmm.CustomIntegrator_step(self, steps)
Exception: Particle coordinate is nan
^C
``` 
This is the code I have been using. Any suggestions or corrections are much appreciated :)

```python
# OpenMM Imports
import simtk.openmm as mm
import simtk.openmm.app as app

# ParmEd Imports
from parmed import load_file, unit as u
from parmed.charmm import CharmmParameterSet
from parmed.openmm import StateDataReporter

# Load the CHARMM files
print('Loading CHARMM files...')
params = CharmmParameterSet('par_opls_aam.inp')
ala2_solv = load_file('ionized.psf')
ala2_crds = load_file('ionized.pdb')

# Compute the box dimensions from the coordinates and set the box lengths (only
# orthorhombic boxes are currently supported in OpenMM)
coords = ala2_crds.positions
min_crds = [coords[0][0], coords[0][1], coords[0][2]]
max_crds = [coords[0][0], coords[0][1], coords[0][2]]

for coord in coords:
    min_crds[0] = min(min_crds[0], coord[0])
    min_crds[1] = min(min_crds[1], coord[1])
    min_crds[2] = min(min_crds[2], coord[2])
    max_crds[0] = max(max_crds[0], coord[0])
    max_crds[1] = max(max_crds[1], coord[1])
    max_crds[2] = max(max_crds[2], coord[2])

ala2_solv.box = [max_crds[0]-min_crds[0],
                 max_crds[1]-min_crds[1],
                 max_crds[2]-min_crds[2],
                 90.0, 90.0, 90.0]

# Create the OpenMM system
print('Creating OpenMM System')
system = ala2_solv.createSystem(params, nonbondedMethod=app.PME,
                                nonbondedCutoff=10.0*u.angstroms,
                                constraints=app.HBonds,
                                switchDistance=9.0*u.angstroms,
)
system.addForce(mm.MonteCarloBarostat(1*u.bar, 300*u.kelvin))
#integrator = mm.amd.AMDIntegrator(2.0*u.femtoseconds,-180590.8,2721.2)

# Create the integrator to do Langevin dynamics
integrator = mm.LangevinIntegrator(
                        300*u.kelvin,       # Temperature of heat bath
                        1.0/u.picoseconds,  # Friction coefficient
                        1.0*u.femtoseconds, # Time step
)

# Define the platform to use; CUDA, OpenCL, CPU, or Reference. Or do not specify
# the platform to use the default (fastest) platform
platform = mm.Platform.getPlatformByName('CUDA') ## Replace this with CUDA on GPU's
prop = dict(CudaPrecision='mixed') # Use mixed single/double precision

# Create the Simulation object
sim = app.Simulation(ala2_solv.topology, system, integrator, platform)

# Set the particle positions
sim.context.setPositions(ala2_crds.positions)

# Minimize the energy
print('Minimizing energy')
sim.minimizeEnergy(maxIterations=500)
sim.reporters.append(app.PDBReporter('trajectory.pdb', 1000))
sim.reporters.append(app.StateDataReporter(stdout, 1000, step=True, 
    potentialEnergy=True, temperature=True, progress=True, remainingTime=True, 
    speed=True, totalSteps=100000, separator='\t'))

# Run dynamics
fin_pos = sim.context.getState(getPositions=True).getPositions()
print('Running dynamics')
sim.step(100000)

## ACCELERATED MD PART 
integrator = mm.amd.AMDIntegrator(2.0*u.femtoseconds,-180590.8,2721.2)
sim = app.Simulation(ala2_solv.topology, system, integrator, platform)
sim.context.setPositions(fin_pos)
sim.reporters.append(app.PDBReporter('trajectory.pdb', 1000))
sim.reporters.append(app.StateDataReporter(stdout, 1000, step=True,
    potentialEnergy=True, temperature=True, progress=True, remainingTime=True,
    speed=True, totalSteps=100000, separator='\t'))

# Run dynamics
fin_pos = sim.context.getState(getPositions=True).getPositions()
print('Running dynamics')
sim.step(100000)
```

**Comment by peastman** [comment]
That error means your simulation is blowing up.  It's hard to guess why, since there are many things that can cause that.  I'm a bit confused by your script, though.  I don't really understand what you're trying to accomplish.

Your first create a LangevinIntegrator and run some dynamics with that.  Is that supposed to be equilibration?  But you then throw away the results of that, create an AMDIntegrator, and run a completely new simulation with that.  Note that you record `fin_pos` *before* you call `sim.step()`.  So it's actually the initial position, not the final position.  Perhaps you could describe exactly what simulation protocol you really want?

Near the top of your script you have a comment saying that OpenMM only supports orthorhombic boxes.  That's not correct.  It supports arbitrary triclinic boxes.  Also, your code for computing the box size could be made much simpler.  Just do this:

```Python
min_crds = min(coords)
max_crds = max(coords)
```

**Comment by leelasd** [comment]
@peastman thanks a lot. I just realized that issue about `fin_step` and I fixed it.  
Thank you so much for quick reply. I will do the modifications to my script.
