### ISSUE TITLE
LennardJonesGenerator fails if NBFixPair has same LJ parameters as atom type

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1914]
I've run into trouble with this ffxml block when creating a force with [`LennardJonesForce` code for `ForceField`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2367-L2388) for the CHARMM forcefield conversion:
```XML
  <LennardJonesForce lj14scale="1.0">
    <Atom epsilon="0.192464" sigma="0.04000135244450124" type="H"/>
    <Atom epsilon="0.192464" sigma="0.04000135244450124" type="HC"/>
    <Atom epsilon="0.092048" sigma="0.2351972615890496" type="HA"/>
    <Atom epsilon="0.12552" sigma="0.24200372779564178" type="HP"/>
    <Atom epsilon="0.092048" sigma="0.2351972615890496" type="HB1"/>
    <Atom epsilon="0.117152" sigma="0.23876085646161097" type="HB2"/>
    <Atom epsilon="0.192464" sigma="0.16036176926526108" type="HR1"/>
    <Atom epsilon="0.192464" sigma="0.1247258205396475" type="HR2"/>
    <Atom epsilon="0.0326352" sigma="0.26156786364600365" type="HR3"/>
    <Atom epsilon="0.41840000000000005" sigma="0.08018088463263054" type="HS"/>
    <Atom epsilon="0.129704" sigma="0.22272467953508485" type="HE1"/>
    <Atom epsilon="0.108784" sigma="0.22450647697136553" type="HE2"/>
    <Atom epsilon="0.18828" sigma="0.23876085646161097" type="HA1"/>
    <Atom epsilon="0.14225600000000002" sigma="0.23876085646161097" type="HA2"/>
    <Atom epsilon="0.100416" sigma="0.23876085646161097" type="HA3"/>
    <Atom epsilon="0.46024000000000004" sigma="0.35635948725613575" type="C"/>
    <Atom epsilon="0.29288000000000003" sigma="0.3550053212045624" type="CA"/>
    <Atom epsilon="0.08368" sigma="0.4053589167538544" type="CT"/>
    <Atom epsilon="0.133888" sigma="0.35635948725613575" type="CT1"/>
    <Atom epsilon="0.234304" sigma="0.35814128469241635" type="CT2"/>
    <Atom epsilon="0.234304" sigma="0.35814128469241635" type="CT2A"/>
    <Atom epsilon="0.32635200000000003" sigma="0.3634866770012585" type="CT3"/>
    <Atom epsilon="0.20920000000000002" sigma="0.32072353853052216" type="CPH1"/>
    <Atom epsilon="0.20920000000000002" sigma="0.32072353853052216" type="CPH2"/>
    <Atom epsilon="0.41421600000000003" sigma="0.3314143231482063" type="CPT"/>
    <Atom epsilon="0.305432" sigma="0.35457768981985505" type="CY"/>
    <Atom epsilon="0.08368" sigma="0.4053589167538544" type="CP1"/>
    <Atom epsilon="0.23012000000000002" sigma="0.3875409423910476" type="CP2"/>
    <Atom epsilon="0.23012000000000002" sigma="0.3875409423910476" type="CP3"/>
    <Atom epsilon="0.29288000000000003" sigma="0.35635948725613575" type="CC"/>
    <Atom epsilon="0.29288000000000003" sigma="0.35635948725613575" type="CD"/>
    <Atom epsilon="0.46024000000000004" sigma="0.39199543598174935" type="CS"/>
    <Atom epsilon="0.28451200000000004" sigma="0.3723956641826618" type="CE1"/>
    <Atom epsilon="0.267776" sigma="0.3706138667463812" type="CE2"/>
    <Atom epsilon="0.305432" sigma="0.35457768981985505" type="CAI"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="N"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NR1"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NR2"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NR3"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NH1"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NH2"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NH3"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NC2"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NY"/>
    <Atom epsilon="0.8368000000000001" sigma="0.3296325257119256" type="NP"/>
    <Atom epsilon="0.50208" sigma="0.30290556416771536" type="O"/>
    <Atom epsilon="0.50208" sigma="0.30290556416771536" type="OB"/>
    <Atom epsilon="0.50208" sigma="0.30290556416771536" type="OC"/>
    <Atom epsilon="0.6363864000000001" sigma="0.31537814622168014" type="OH1"/>
    <Atom epsilon="0.6363864000000001" sigma="0.31537814622168014" type="OS"/>
    <Atom epsilon="1.8828" sigma="0.35635948725613575" type="S"/>
    <Atom epsilon="1.58992" sigma="0.35190499366543404" type="SM"/>
    <Atom epsilon="1.96648" sigma="0.39199543598174935" type="SS"/>
    <Atom epsilon="0.192464" sigma="0.04000135244450124" type="HT"/>
    <Atom epsilon="0.192464" sigma="0.04000135244450124" type="HX"/>
    <Atom epsilon="0.6363864000000001" sigma="0.3150574226831496" type="OT"/>
    <Atom epsilon="0.50208" sigma="0.30290556416771536" type="OX"/>
    <Atom epsilon="0.00974872" sigma="0.23118821735741807" type="LIT"/>
    <Atom epsilon="0.1962296" sigma="0.2513670733232967" type="SOD"/>
    <Atom epsilon="0.06276" sigma="0.2111429961992604" type="MG"/>
    <Atom epsilon="0.364008" sigma="0.3142645228240047" type="POT"/>
    <Atom epsilon="0.50208" sigma="0.24357170953956878" type="CAL"/>
    <Atom epsilon="0.6276" sigma="0.3385415128933289" type="RUB"/>
    <Atom epsilon="0.79496" sigma="0.37417746161894255" type="CES"/>
    <Atom epsilon="0.6276" sigma="0.33675971545704825" type="BAR"/>
    <Atom epsilon="1.046" sigma="0.194215920554594" type="ZN"/>
    <Atom epsilon="0.50208" sigma="0.2417899121032881" type="CAD"/>
    <Atom epsilon="0.6276" sigma="0.4044680180357141" type="CLA"/>
    <NBFixPair epsilon="0.35093300000000005" sigma="0.6647886234763212" type1="CLA" type2="SOD"/>
    <NBFixPair epsilon="0.477963424" sigma="0.727151533746145" type1="CLA" type2="POT"/>
    <NBFixPair epsilon="0.31388368000000005" sigma="0.5683933821735365" type1="OC" type2="SOD"/>
    <NBFixPair epsilon="0.31388368000000005" sigma="0.5683933821735365" type1="OCL" type2="SOD"/>
    <NBFixPair epsilon="0.31388368000000005" sigma="0.5683933821735365" type1="OC2D2" type2="SOD"/>
    <NBFixPair epsilon="0.31388368000000005" sigma="0.5683933821735365" type1="OG2D2" type2="SOD"/>
  </LennardJonesForce>
```
Processing it with `ForceField` gives an exception: 
```
======================================================================
ERROR: Test writing XML parameter files from Charmm parameter files and reading them back into OpenMM ForceField
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/github/parmed/ParmEd/test/test_parmed_openmm.py", line 601, in test_write_xml_parameters_charmm
    system = forcefield.createSystem(pdbfile.topology, nonbondedMethod=app.NoCutoff)
  File "/Users/choderaj/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1270, in createSystem
    force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
  File "/Users/choderaj/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 2390, in createForce
    reverseMap[typeMap[typeValue]] = typeValue
IndexError: list assignment index out of range
```
which appears to be due to the fact that some entries of [`typeMap`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2374) are overwritten, which I presume is because some `NBFixPair` entries have the same LJ parameters as one of the atom types. Here's the contents of `typeMap` every iteration of [this loop](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2375-L2385):
```
{(0.3296325257119256, 0.8368000000000001): 0}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 7, (0.35635948725613575, 0.29288000000000003): 8}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 9, (0.35635948725613575, 0.29288000000000003): 8}
{(0.3296325257119256, 0.8368000000000001): 0, (0.04000135244450124, 0.192464): 1, (0.35635948725613575, 0.133888): 2, (0.2351972615890496, 0.092048): 3, (0.3634866770012585, 0.32635200000000003): 4, (0.23876085646161097, 0.100416): 5, (0.35635948725613575, 0.46024000000000004): 6, (0.30290556416771536, 0.50208): 10, (0.35635948725613575, 0.29288000000000003): 8}
```

**Comment by jchodera** [comment]
Fixed by #1915.
