### ISSUE TITLE
ValueError: Energy is NaN

### ISSUE THREAD

**Issue by duxinzheng** [pandegroup/openmm#1936]
Has anyone met this error before?

**Traceback (most recent call last):
  File "simulateGromacs.py", line 61, in <module>
    print('Running dynamics')
  File "/home/tools/Python-2.7.2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 132, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/tools/Python-2.7.2/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 219, in _simulate
    reporter.report(self, state)
  File "/home/tools/Python-2.7.2/lib/python2.7/site-packages/simtk/openmm/app/statedatareporter.py", line 195, in report
    self._checkForErrors(simulation, state)
  File "/home/tools/Python-2.7.2/lib/python2.7/site-packages/simtk/openmm/app/statedatareporter.py", line 347, in _checkForErrors
    raise ValueError('Energy is NaN')
ValueError: Energy is NaN**

I use the gpu platform.The pdb file can be read and loaded, and the OpenMM System can be created, the energy seems to be Minimizing. This(maybe the Minimizing) lasts all day(about 24hours) and task manager says the gpu is occupied. However no output files occur and the error ocurrs.
Thanks a lot.

**Comment by peastman** [comment]
Try minimizing with the CPU platform.  It's possible your initial conformation has really severe clashes, producing forces larger than the CUDA platform can handle.  Once it's minimized, it should work fine with the GPU.

**Comment by mainguyenanhvu** [comment]
This error could be fixed if we are increase GPU memory? For example, we can increase 16GB GPU to 32GB.
I would like to run with GPU because it saves time a lot. Please help me. 

Thank you.

**Comment by peastman** [comment]
No, it's unrelated to the amount of GPU memory.  It happens when a force exceeds the maximum value it can represent with 64 bit fixed point (about 2 billion kJ/mol/nm).

**Comment by mainguyenanhvu** [comment]
How can I change the number of bit for force variable? 
I use this code to add custom forces:
`
    pdb = openmm.app.pdbfile.PDBFile(args.filename)
    spring_constant = args.spring_constant * unit.kilojoule/unit.mole/unit.nanometer**2
    velocity = args.velocity * unit.nanometer/unit.picosecond
    direction = unit.Quantity(args.direction, unit.nanometer)
    smd_force = openmm.CustomExternalForce("k*((x-x0)^2+(y-y0)^2+(z-z0)^2)^0.5 + v*(x-x0)*dir_x + v*(y-y0)*dir_y + v*(z-z0)*dir_z")
    smd_force.addGlobalParameter("k", spring_constant)
    smd_force.addGlobalParameter("v", velocity)
    smd_force.addGlobalParameter("dir_x", direction[0]/unit.nanometer)
    smd_force.addGlobalParameter("dir_y", direction[1]/unit.nanometer)
    smd_force.addGlobalParameter("dir_z", direction[2]/unit.nanometer)
    smd_force.addPerParticleParameter("x0")
    smd_force.addPerParticleParameter("y0")
    smd_force.addPerParticleParameter("z0")
    for index in range(len(pdb.positions)):
        x, y, z = pdb.positions[index]
        smd_force.addParticle(index, [x, y, z])
    system.addForce(smd_force)

`

**Comment by mainguyenanhvu** [comment]
This is my error:
`running 50000 equilibration steps, saving every 10000 steps
#"Temperature (K)"
695.738665325081
Traceback (most recent call last):
  File "/home/tools/root/core/examples/../mdtools/mdtools/run_smd.py", line 479, in <module>
    main()
  File "/home/tools/root/core/examples/../mdtools/mdtools/run_smd.py", line 444, in main
    simulation.step(equisteps)
  File "/home/.conda/envs/lib/python3.10/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/.conda/envs/lib/python3.10/site-packages/openmm/app/simulation.py", line 241, in _simulate
    self._generate_reports(wrapped, True)
  File "/home/.conda/envs/lib/python3.10/site-packages/openmm/app/simulation.py", line 263, in _generate_reports
    reporter.report(self, state)
  File "/home/.conda/envs/lib/python3.10/site-packages/mdtraj/reporters/basereporter.py", line 216, in report
    self._checkForErrors(simulation, state)
  File "/home/.conda/envs/lib/python3.10/site-packages/mdtraj/reporters/basereporter.py", line 261, in _checkForErrors
    raise ValueError('Energy is NaN')
ValueError: Energy is NaN

`
