### ISSUE TITLE
Failure to compile OpenCL kernels

### ISSUE THREAD

**Issue by pgrinaway** [pandegroup/openmm#2082]
As I was putting some finishing touches on exception fixes, I ended up with an unusual error (at bottom, it's quite long). The code I used to reproduce this error is here:

```python
import numpy as np
from simtk import openmm, unit

hybrid_positions = np.load("hybrid_positions.npy")

with open("hybrid_system.xml", 'r') as infile:
    hybrid_system = openmm.XmlSerializer.deserialize(infile.read())

integrator = openmm.VerletIntegrator(1.0*unit.femtoseconds)
platform = openmm.Platform.getPlatformByName("OpenCL")
ctx = openmm.Context(hybrid_system, integrator, platform)
ctx.setPositions(hybrid_positions)

openmm.LocalEnergyMinimizer.minimize(ctx)


```
Version '7.2.0.dev-69aa676'

Compressed files to use for input:
[hybrid_system.tar.gz](https://github.com/pandegroup/openmm/files/2033272/hybrid_system.tar.gz)

[hybrid_positions.tar.gz](https://github.com/pandegroup/openmm/files/2033273/hybrid_positions.tar.gz)

```
OpenCL internal error: [CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: Build Program driver returned (10015)
OpenCL internal error: OpenCL Warning : clBuildProgram failed: could not build program for 0x1024500 (HD Graphics 5000) (err:-2)
OpenCL internal error: [CL_BUILD_ERROR] : OpenCL Build Error : Compiler build log:
<program source>:57:7: error: duplicate member 'sigmaEpsilon_x'
float sigmaEpsilon_x;
      ^
<program source>:55:11: note: previous declaration is here
    float sigmaEpsilon_x;
          ^
<program source>:58:7: error: duplicate member 'sigmaEpsilon_y'
float sigmaEpsilon_y;
      ^
<program source>:56:7: note: previous declaration is here
float sigmaEpsilon_y;
      ^
<program source>:81:96: error: redefinition of parameter 'global_sigmaEpsilon'
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                                                                               ^
<program source>:81:43: note: previous declaration is here
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                          ^
<program source>:81:96: error: parameter name omitted
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                                                                               ^
<program source>:102:8: error: redefinition of 'sigmaEpsilon1'
float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
       ^
<program source>:101:16: note: previous definition is here
        float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
               ^
<program source>:133:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:132:24: note: previous definition is here
                float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                       ^
<program source>:194:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:324:8: error: redefinition of 'temp_sigmaEpsilon'
float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
       ^
<program source>:321:20: note: previous definition is here
            float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
                   ^
<program source>:350:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:349:28: note: previous definition is here
                    float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                           ^
<program source>:411:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:633:8: error: redefinition of 'sigmaEpsilon1'
float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
       ^
<program source>:632:20: note: previous definition is here
            float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
                   ^
<program source>:651:8: error: redefinition of 'temp_sigmaEpsilon'
float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
       ^
<program source>:648:24: note: previous definition is here
                float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
                       ^
<program source>:686:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:685:32: note: previous definition is here
                        float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                               ^
<program source>:747:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:892:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:891:32: note: previous definition is here
                        float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                               ^
<program source>:953:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:94:44: warning: comparison of integers of different signs: 'int' and 'const unsigned int'
    for (int pos = firstExclusionTile; pos < lastExclusionTile; pos++) {
                                       ~~~ ^ ~~~~~~~~~~~~~~~~~
<program source>:154:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:371:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:707:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:913:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~


Traceback (most recent call last):
  File "reproduce_failure.py", line 14, in <module>
    openmm.LocalEnergyMinimizer.minimize(ctx)
  File "/Users/grinawap/anaconda3/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 15129, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
Exception: Error compiling kernel: <program source>:57:7: error: duplicate member 'sigmaEpsilon_x'
float sigmaEpsilon_x;
      ^
<program source>:55:11: note: previous declaration is here
    float sigmaEpsilon_x;
          ^
<program source>:58:7: error: duplicate member 'sigmaEpsilon_y'
float sigmaEpsilon_y;
      ^
<program source>:56:7: note: previous declaration is here
float sigmaEpsilon_y;
      ^
<program source>:81:96: error: redefinition of parameter 'global_sigmaEpsilon'
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                                                                               ^
<program source>:81:43: note: previous declaration is here
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                          ^
<program source>:81:96: error: parameter name omitted
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                                                                               ^
<program source>:102:8: error: redefinition of 'sigmaEpsilon1'
float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
       ^
<program source>:101:16: note: previous definition is here
        float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
               ^
<program source>:133:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:132:24: note: previous definition is here
                float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                       ^
<program source>:194:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:324:8: error: redefinition of 'temp_sigmaEpsilon'
float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
       ^
<program source>:321:20: note: previous definition is here
            float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
                   ^
<program source>:350:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:349:28: note: previous definition is here
                    float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                           ^
<program source>:411:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:633:8: error: redefinition of 'sigmaEpsilon1'
float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
       ^
<program source>:632:20: note: previous definition is here
            float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
                   ^
<program source>:651:8: error: redefinition of 'temp_sigmaEpsilon'
float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
       ^
<program source>:648:24: note: previous definition is here
                float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
                       ^
<program source>:686:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:685:32: note: previous definition is here
                        float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                               ^
<program source>:747:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:892:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:891:32: note: previous definition is here
                        float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                               ^
<program source>:953:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:94:44: warning: comparison of integers of different signs: 'int' and 'const unsigned int'
    for (int pos = firstExclusionTile; pos < lastExclusionTile; pos++) {
                                       ~~~ ^ ~~~~~~~~~~~~~~~~~
<program source>:154:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:371:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:707:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:913:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~

```

**Comment by pgrinaway** [comment]
Hm, maybe this is an old version of OpenMM. I'm updating and re-trying now.

**Comment by pgrinaway** [comment]
Ok, it still happens. Attached are the relevant files for the run with the new version (not sure if it really matters, but in case it does, I'm attaching them). 
[hybrid_positions.tar.gz](https://github.com/pandegroup/openmm/files/2033292/hybrid_positions.tar.gz)
[hybrid_system.tar.gz](https://github.com/pandegroup/openmm/files/2033293/hybrid_system.tar.gz)

**Comment by pgrinaway** [comment]
@jchodera and I were speculating that this could be because there are two `NonbondedForce`s acting on the system, and that when the kernels get fused some variables get defined twice. Here is an even simpler example demonstrating the issue:

```python
positions = np.array([[0.23924777, 0.89168393, 0.62865526],
                       [0.97949665, 0.38314063, 0.56043033]])

def reproduce_experiment(platform_name="OpenCL"):
    try_params = []

    try_params.append([1.0, 1.0, 0.0])
    try_params.append([0.0, 1.0, 0.8])
    try_params.append([1.0, 1.0, 0.8])
    
    platform = openmm.Platform.getPlatformByName(platform_name)
    for param_set in try_params:
        print("trying " + str(param_set))

        nbforce1 = openmm.NonbondedForce()
        nbforce2 = openmm.NonbondedForce()
        system = openmm.System()

        system.addParticle(1.0)
        system.addParticle(1.0)

        nbforce1.addParticle(param_set[0], param_set[1], param_set[2])
        nbforce1.addParticle(param_set[0], param_set[1], param_set[2])
        
        nbforce2.addParticle(param_set[0], param_set[1], param_set[2])
        nbforce2.addParticle(param_set[0], param_set[1], param_set[2])

        integrator = openmm.VerletIntegrator(1.0)

        system.addForce(nbforce1)
        system.addForce(nbforce2)

        ctx = openmm.Context(system, integrator, platform)
        ctx.setPositions(positions)

        ctx.getState(getEnergy=True).getPotentialEnergy()
```

**Comment by peastman** [comment]
It looks like it's unhappy about having two different NonbondedForces in the same system (the one created internally by the CustomCVForce).  Hopefully this will be easy to fix.  I wonder if it's related to #2083?

**Comment by pgrinaway** [comment]
>It looks like it's unhappy about having two different NonbondedForces in the same system (the one created internally by the CustomCVForce). Hopefully this will be easy to fix. I wonder if it's related to #2083?

Possibly. What's interesting is that it doesn't seem to mind having two `NonbondedForce`s as long as they only have electrostatics. When I have non-zero LJ parameters in both, it gets very unhappy.

**Comment by peastman** [comment]
It's the result of https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLKernels.cpp#L1872-L1873:

```c++
if (hasLJ)
    cl.getNonbondedUtilities().addParameter(OpenCLNonbondedUtilities::ParameterInfo("sigmaEpsilon", "float", 2, sizeof(cl_float2), sigmaEpsilon.getDeviceBuffer()));
```

It adds a parameter to the nonbonded kernel, and hardcodes the name `sigmaEpsilon`.  If you have two NonbondedForces, they each try to add a parameter with the same name, leading to the compilation error.  If all the epsilons are 0, then `hasLJ` is false and it doesn't add the parameter.

This should be easy to fix.

**Comment by pgrinaway** [comment]
ahhh. Awesome, thanks!!

**Comment by jchodera** [comment]
Good catch!

Will we run into #2083 since we have two NonbondedForces with different partial charges in the same CustomCVForce?

**Comment by peastman** [comment]
Yes, I think so.
