### ISSUE TITLE
"RuntimeError: Expected atoms table not found" when converting leaprc.ff10 to ffxml

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2158]
I'm trying to update the OpenMM Amber forcefield conversion to use AmberTools 18 in https://github.com/choderalab/openmm-forcefields/pull/66 but am running into this error converting `leaprc.ff10`:
```
Converting /Users/choderaj/miniconda/bin/../dat/leap/cmd/oldff/leaprc.ff10 to ffxml...
Preprocessing the leaprc for ff10...
Converting to ffxml ffxml/ff10.xml...
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue SEP
  'residue %s' % (n, nres+1, name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue H2D
  'residue %s' % (n, nres+1, name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue S1P
  'residue %s' % (n, nres+1, name), AmberWarning)
Traceback (most recent call last):
  File "convert_amber.py", line 1214, in <module>
    main()
  File "convert_amber.py", line 105, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 381, in convert_yaml
    filter_warnings=filter_warnings, split_filename=True)
  File "convert_amber.py", line 205, in convert_leaprc
    params = parmed.amber.AmberParameterSet.from_leaprc(leaprc)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/parameters.py", line 298, in from_leaprc
    params.residues.update(AmberOFFLibrary.parse(_find_amber_file(fname, search_oldff)))
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py", line 138, in parse
    raise RuntimeError('Expected atoms table not found')
RuntimeError: Expected atoms table not found
```
Any idea what may have changed in parmed that would affect the conversion of this forcefield?

**Comment by peastman** [comment]
Did you mean to post this on the ParmEd, not the OpenMM tracker?
