### ISSUE TITLE
NaN coordinates in benchmark.py with 4 gpus

### ISSUE THREAD

**Issue by fabiotrovato** [pandegroup/openmm#2286]
Hi,

I have installed openMM v 7.3.1 and I was trying to understand the examples in benchmark.py. Using one of those examples, I wanted to test whether I could achieve a speedup using more gpus (each slurm script is executed with sbatch).

This is the slurm script I used for a run on 1 gpu:
```
#!/bin/bash
#SBATCH -p gpu
#SBATCH --gres=gpu:1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=1:00:00
#SBATCH --export=ALL
module load cuda/9.0
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"

python benchmark.py --platform=CUDA --test=amoebapme --device=0
```

which gives the following output:

```
Module for cuda 8.0 loaded.
CUDA_VISIBLE_DEVICES: 0
Platform: CUDA
Precision: single
Device: 0

Test: amoebapme (epsilon=1e-05)
Step Size: 2 fs
Integrated 2353 steps in 55.383 seconds
7.34157 ns/day
```

If I use a similar script, which I assume correct for testing the performance of 4 gpus:

```
#!/bin/bash
#SBATCH -p gpu
#SBATCH --gres=gpu:4
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=1:00:00
#SBATCH --export=ALL
module load cuda/9.0
echo "CUDA_VISIBLE_DEVICES: $CUDA_VISIBLE_DEVICES"

python benchmark.py --platform=CUDA --test=amoebapme --device=0,1,2,3
```
this output results (nan coordinates):

```
CUDA_VISIBLE_DEVICES: 0,1,2,3
Platform: CUDA
Precision: single
Device: 0,1,2,3

Test: amoebapme (epsilon=1e-05)
here
Step Size: 1 fs
Traceback (most recent call last):
  File "benchmark.py", line 163, in <module>
    runOneTest(options.test, options)
  File "benchmark.py", line 120, in runOneTest
    time = timeIntegration(context, steps, initialSteps)
  File "benchmark.py", line 14, in timeIntegration
    context.getIntegrator().step(steps)
  File "/home/trovato/miniconda3/envs/openmm_cuda9.0/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18984, in step
    return _openmm.CustomIntegrator_step(self, steps)
Exception: Particle coordinate is nan
```

I would appreciate if you could suggest me what I might be doing wrong.
Thank you,
Fabio

**Comment by peastman** [comment]
The AMOEBA implementation doesn't support using multiple GPUs.  Because of the induced dipoles, AMOEBA nonbonded interactions aren't pairwise, which makes it a lot more difficult to parallelize across multiple devices.

**Comment by fabiotrovato** [comment]
Thank you for the clarification!

Best,
Fabio
