### ISSUE TITLE
Attempting to get an undefined CustomIntegrator global parameter causes segfaults

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2298]
Attempting to get a global `CustomIntegrator` value that doesn't exist results in a segfault, rather than an exception, on `osx` with OpenMM 7.3.1:
```
>>> from simtk import openmm
>>> integrator = openmm.CustomIntegrator(0.001)
>>> integrator.getGlobalVariableByName('x')
python(18875,0x7fff8a4bf380) malloc: *** error for object 0x7febad66a0f8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by jchodera** [comment]
On `linux` with 7.3.1, I get an `Exception` as expected:
```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from simtk import openmm
>>> integrator = openmm.CustomIntegrator(0.001)
>>> integrator.getGlobalVariableByName('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chodera/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18597, in getGlobalVariableByName
    return _openmm.CustomIntegrator_getGlobalVariableByName(self, name)
Exception: Illegal global variable name: x
```
Let me try on a few more `osx` machines.

**Comment by jchodera** [comment]
Specifically, the segfaults occur on OS X 10.13.6.

`conda` environment details:
```
# packages in environment at /Users/choderaj/miniconda:
#
# Name                    Version                   Build  Channel
openmm                    7.3.1           py37_cuda92_rc_2    omnia
openmmtools               0.19.0                   pypi_0    pypi
mski1776:openmmtools choderaj$ conda list
# packages in environment at /Users/choderaj/miniconda:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
ambermini                 16.16.0                       7    omnia
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     19.1.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
beautifulsoup4            4.7.1                 py37_1001    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.16.3               h0a44026_0    conda-forge
boost                     1.68.0          py37h9888f84_1001    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
bson                      0.5.8                      py_0    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            h9247486_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.2           py37h2d6ddff_1    conda-forge
cftime                    1.0.3.4         py37h917ab60_1000    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
conda                     4.6.12                   py37_0    conda-forge
conda-build               3.17.8                   py37_1    conda-forge
conda-env                 2.6.0                         1    conda-forge
cryptography              2.6.1            py37h212c5bf_0    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
cython                    0.29.6           py37h0a44026_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
docutils                  0.14                  py37_1001    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
fftw3f                    3.3.4                         2    omnia
filelock                  3.0.10                     py_0    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.58.3            h2836805_1001    conda-forge
glob2                     0.6                        py_0    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
latexcodec                1.0.6                      py_0    conda-forge
libarchive                3.3.3             heb9f7fe_1003    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
liblief                   0.9.0                h2a1bed3_1    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.36            ha441bb4_1000    conda-forge
libsolv                   0.7.3                hfbae3c0_2    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            h344961e_1002    conda-forge
libxml2                   2.9.8             hf14e9c8_1005    conda-forge
lz4-c                     1.8.1.2                       0    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
m2r                       0.2.1                      py_0    conda-forge
mamba                     0.0.3            py37h770b8ee_0    conda-forge/label/mamba-alpha
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
mdtraj                    1.9.2           py37h13be62f_1000    conda-forge
mistune                   0.8.4           py37h1de35cc_1000    conda-forge
mock                      2.0.0                 py37_1001    conda-forge
mpiplus                   v0.0.1                py37_1000    conda-forge
msgpack-python            0.6.1            py37h04f5b5a_0    conda-forge
nbconvert                 5.4.1                      py_2    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nbsphinx                  0.4.2                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf4                   1.5.0.1          py37h58b02fa_0    conda-forge
networkx                  2.2                        py_1    conda-forge
nose                      1.3.7                 py37_1002    conda-forge
numexpr                   2.6.9           py37h1702cab_1000    conda-forge
numpy                     1.16.2           py37hbb3c62a_1    conda-forge
numpydoc                  0.8.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             h436c29b_1001    conda-forge
openforcefield            0.2.1                    py37_0    omnia
openmm                    7.3.1           py37_cuda92_rc_2    omnia
openmmtools               0.19.0                   pypi_0    pypi
openssl                   1.1.1b               h01d97ff_2    conda-forge
oset                      0.1.3                      py_1    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py37h0a44026_0    conda-forge
pandoc                    2.7.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parmed                    3.1.0                    py37_0    omnia
pbr                       5.1.3                      py_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pillow                    6.0.0            py37h7095ceb_0    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pixman                    0.34.0            h1de35cc_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.6.1            py37h1de35cc_0    conda-forge
py-lief                   0.9.0            py37h6d6d4d2_1    conda-forge
pybtex                    0.22.2                   py37_0    conda-forge
pybtex-docutils           0.2.1                 py37_1000    conda-forge
pycairo                   1.18.0           py37ha54c0a8_0  
pycosat                   0.6.3           py37h1de35cc_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pymbar                    3.0.3            py37h7eb728f_3    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyrsistent                0.14.11          py37h1de35cc_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
pytables                  3.5.1            py37h689b3ec_1    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
python.app                1.2             py37h1de35cc_1200    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    5.1              py37h1de35cc_0    conda-forge
rdkit                     2019.03.1        py37haff9cca_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
ruamel_yaml               0.15.71         py37h1de35cc_1000    conda-forge
scipy                     1.2.1            py37hbd7caa9_1    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
soupsieve                 1.9                      py37_0    conda-forge
sphinx                    2.0.1                      py_0    conda-forge
sphinx_bootstrap_theme    0.6.4                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-bibtex      0.4.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
sqlite                    3.26.0            h1765d9f_1001    conda-forge
testpath                  0.3.1                    py37_1    conda-forge
tk                        8.6.9             ha441bb4_1001    conda-forge
toml                      0.10.0                     py_0    conda-forge
tqdm                      4.31.1                     py_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.3.3                         1    conda-forge
```

**Comment by jchodera** [comment]
Hm, I can't reproduce this on other `osx` boxes with OpenMM 7.3.1 installed via `conda`. This must be a peculiarity of this environment where exceptions are triggering segfaults. I'll close this and #2300 for now.
