### ISSUE TITLE
CUDA_ERROR_INVALID_PTX error when creating many exclusions

### ISSUE THREAD

**Issue by fabian-paul** [pandegroup/openmm#2325]
Hi all,

I have recently attempted to create a dummy atom in OpenMM - without success. I was following @peastman's [recipe](https://github.com/pandegroup/openmm/issues/2262#issuecomment-464157489) with a slight change. Instead of restraining an atom in absolute space I wanted to restrain the center of mass of a group of atoms in space. This entails creating a dummy atom with its interaction with all other atoms switched off. At least with CUDA 7.5 this does not work.

Here is a minimal example for the problem: [dummy-atom.py.txt](https://github.com/pandegroup/openmm/files/3308024/dummy-atom.py.txt). This is mostly @peastman's [recipe](https://github.com/pandegroup/openmm/issues/2262#issuecomment-464157489). When I run this I get the following error:

```
$ python dummy-atom.py 
Traceback (most recent call last):
  File "dummy-atom.py", line 36, in <module>
    print('Initial energy:', context.getState(getEnergy=True).getPotentialEnergy())
  File "/home/fab/opt/anaconda3/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 12166, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
Exception: Error loading CUDA module: CUDA_ERROR_INVALID_PTX (218)
```

The error only occurs if the number of exclusions is quite large. I replaced the DHFR example with the APOA1 example to produce the problem. Also if I leave some atoms unexcluded,  the simulation runs. So this seems to be some hidden memory or allocation error.

I can reproduce the problem on my GeForce GTX 780  and Quadro K2200 cards. I'm using CUDA 7.5

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

```
$ conda list | grep openmm
openmm                    7.3.0           py36_cuda75_rc_1    omnia/label/cuda75
```

Thanks,
Fabian

**Comment by peastman** [comment]
It's possible you're just running out of memory.  The GTX 780 and Quadro K2200 only have 3 GB and 4 GB respectively, which isn't much by modern standards.  Also make sure nothing else is taking up a lot of device memory.  Try running `nvidia-smi` just before you start the simulation to see how much memory is available, then use it to watch the device memory as the simulation starts up and see whether it's hitting the limit.

**Comment by fabian-paul** [comment]
No, I sure it's not a **total** memory issue. There is something more complicated going on.
The simulation runs, if I use up to 29632 extra exclusions (in addition to the exclusions/exceptions that are already present in the force field.) If I add one more exception (29633), I get the error.
This behavior persists, if I shut down the X window system and run the script in text mode. This frees up 365 MB on the GPU. Still, the maximal number of exclusions stays at exactly 29632. Adding one more exclusion while in text mode leads to the error.

**Comment by fabian-paul** [comment]
I've also updated CUDA to version 10 and reinstalled OpenMM. Same problem.

**Comment by fabian-paul** [comment]
The magic number 29632 is also independent from the molecular system that I try to simulate!

**Comment by SamikBose** [comment]
Hi @fabian-paul, have you been able to solve the issue. I am getting the exactly same error with my code which uses openmm 7.5.1 and cuda 11.1? There no such problem with other platforms like OpenCL.
