### ISSUE TITLE
AMOEBA system setup issue with OpenMM app

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#428]
I've run into this error message:
```
**********************************************************************
File "repex/testsystems.py", line 2501, in testsystems.AMOEBAIonBox
Failed example:
    testsystem = AMOEBAIonBox()
Exception raised:
    Traceback (most recent call last):
      File "/Users/choderaj/anaconda/lib/python2.7/doctest.py", line 1289, in __run
        compileflags, 1) in test.globs
      File "<doctest testsystems.AMOEBAIonBox[0]>", line 1, in <module>
        testsystem = AMOEBAIonBox()
      File "repex/testsystems.py", line 2511, in __init__
        system = ff.createSystem(pdbfile.topology, nonbondedMethod=app.PME, constraints=app.HBonds, useDispersionCorrection=True, nonbondedCutoff=7.0*unit.angstroms)
      File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 472, in createSystem
        force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
      File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 2942, in createForce
        force.setUseDispersionCorrection(int(args['useDispersionCorrection']))
      File "/Users/choderaj/code/yank/install/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 3454, in setUseDispersionCorrection
        return _openmm.AmoebaVdwForce_setUseDispersionCorrection(self, *args)
    TypeError: in method 'AmoebaVdwForce_setUseDispersionCorrection', argument 2 of type 'bool'
Trying:
    system, positions = testsystem.system, testsystem.positions
Expecting nothing
**********************************************************************
```
which seems to be due to this line:
https://github.com/SimTk/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2942

I'll submit a PR to fix as soon as I get a chance.

**Comment by jchodera** [comment]
I believe this was fixed by #491.
