### ISSUE TITLE
Reference Amoeba segfault

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#597]
I'm getting a segfault when I try to run PME with the AMOEBA force field.  I'm very hopeful this can get fixed before release.

Here's my Python script:
```Python
#!/usr/bin/env python

from simtk.openmm import app
from simtk import openmm as mm, unit as u
from sys import stdout

pdb = app.PDBFile('jac.pdb')
pdb.topology.setUnitCellDimensions(mm.Vec3(60, 60, 60) * u.angstroms)
forcefield = app.ForceField('amoeba2013.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.PME,
                                 nonbondedCutoff=8*u.angstroms)
integrator = mm.VerletIntegrator(1.0*u.femtoseconds)
simulation = app.Simulation(pdb.topology, system, integrator,
                            mm.Platform.getPlatformByName('Reference'))
simulation.context.setPositions(pdb.positions)
simulation.reporters.append(
        app.StateDataReporter(stdout, 1, step=True,
                              potentialEnergy=True, temperature=True)
)
simulation.step(1)

print 'Done!'
```

The PDB file is available at https://www.dropbox.com/s/wyrkv95ytmexwfu/jac.pdb

Here's the stack trace I got from a core dump (I added some print statements, so the line numbers may be off by 1 or 2):

```
Program terminated with signal 11, Segmentation fault.
#0  0x00007fc94c2fee74 in AmoebaReferencePmeMultipoleForce::findAmoebaAtomRangeForGrid (this=0x4b33f10, 
    particleData=...)
    at /home/swails/src/openmm/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp:5082
5082	                _pmeAtomRange[jj] = ii;
(gdb) backtrace
#0  0x00007fc94c2fee74 in AmoebaReferencePmeMultipoleForce::findAmoebaAtomRangeForGrid (this=0x4b33f10, 
    particleData=std::vector of length 23558, capacity 23558 = {...})
    at /home/swails/src/openmm/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp:5082
#1  0x00007fc94c2fded2 in AmoebaReferencePmeMultipoleForce::calculateFixedMultipoleField (this=0x4b33f10, 
    particleData=std::vector of length 23558, capacity 23558 = {...})
    at /home/swails/src/openmm/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp:4926
#2  0x00007fc94c2c2fac in AmoebaReferenceMultipoleForce::calculateInducedDipoles (this=0x4b33f10, 
    particleData=std::vector of length 23558, capacity 23558 = {...})
    at /home/swails/src/openmm/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp:927
#3  0x00007fc94c2cc6fd in AmoebaReferenceMultipoleForce::setup (this=0x4b33f10, 
    particlePositions=std::vector of length 23558, capacity 23558 = {...}, 
    charges=std::vector of length 23558, capacity 23558 = {...}, 
    dipoles=std::vector of length 70674, capacity 70674 = {...}, 
    quadrupoles=std::vector of length 212022, capacity 212022 = {...}, 
    tholes=std::vector of length 23558, capacity 23558 = {...}, 
    dampingFactors=std::vector of length 23558, capacity 23558 = {...}, 
    polarity=std::vector of length 23558, capacity 23558 = {...}, 
    axisTypes=std::vector of length 23558, capacity 23558 = {...}, 
    multipoleAtomZs=std::vector of length 23558, capacity 23558 = {...}, 
    multipoleAtomXs=std::vector of length 23558, capacity 23558 = {...}, 
    multipoleAtomYs=std::vector of length 23558, capacity 23558 = {...}, 
    multipoleAtomCovalentInfo=std::vector of length 23558, capacity 23558 = {...}, 
    particleData=std::vector of length 23558, capacity 23558 = {...})
    at /home/swails/src/openmm/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp:1626
#4  0x00007fc94c2cc91b in AmoebaReferenceMultipoleForce::calculateForceAndEnergy (this=0x4b33f10, 
---Type <return> to continue, or q <return> to quit---
    particlePositions=std::vector of length 23558, capacity 23558 = {...}, 
    charges=std::vector of length 23558, capacity 23558 = {...}, 
    dipoles=std::vector of length 70674, capacity 70674 = {...}, 
    quadrupoles=std::vector of length 212022, capacity 212022 = {...}, 
    tholes=std::vector of length 23558, capacity 23558 = {...}, 
    dampingFactors=std::vector of length 23558, capacity 23558 = {...}, 
    polarity=std::vector of length 23558, capacity 23558 = {...}, 
    axisTypes=std::vector of length 23558, capacity 23558 = {...}, 
    multipoleAtomZs=std::vector of length 23558, capacity 23558 = {...}, 
    multipoleAtomXs=std::vector of length 23558, capacity 23558 = {...}, 
    multipoleAtomYs=std::vector of length 23558, capacity 23558 = {...}, 
    multipoleAtomCovalentInfo=std::vector of length 23558, capacity 23558 = {...}, 
    forces=std::vector of length 23558, capacity 23558 = {...})
    at /home/swails/src/openmm/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp:1661
#5  0x00007fc94c33dc62 in OpenMM::ReferenceCalcAmoebaMultipoleForceKernel::execute (this=0x3fcc2e0, context=..., 
    includeForces=true, includeEnergy=true)
    at /home/swails/src/openmm/plugins/amoeba/platforms/reference/src/AmoebaReferenceKernels.cpp:679
#6  0x00007fc952816f06 in OpenMM::AmoebaMultipoleForceImpl::calcForcesAndEnergy (this=0xd664e0, context=..., 
    includeForces=true, includeEnergy=true, groups=-1)
    at /home/swails/src/openmm/plugins/amoeba/openmmapi/src/AmoebaMultipoleForceImpl.cpp:131
#7  0x00007fc952c8eb80 in OpenMM::ContextImpl::calcForcesAndEnergy (this=0x35cd460, includeForces=true, 
    includeEnergy=true, groups=-1) at /home/swails/src/openmm/openmmapi/src/ContextImpl.cpp:265
#8  0x00007fc952c88036 in OpenMM::Context::getState (this=0xd79770, types=24, enforcePeriodicBox=true, groups=-1)
    at /home/swails/src/openmm/openmmapi/src/Context.cpp:88
#9  0x00007fc95324af5d in OpenMM_Context__getStateAsLists(OpenMM::Context*, int, int, int, int, int, int, int) ()
   from /usr/local/openmm/debug/openmm/python2.7/simtk/openmm/_openmm.so
#10 0x00007fc9532b1813 in _wrap_Context__getStateAsLists ()
   from /usr/local/openmm/debug/openmm/python2.7/simtk/openmm/_openmm.so
---Type <return> to continue, or q <return> to quit---
```

The rest of the frames are uninteresting function calls within Python.  Any ideas?

**Comment by swails** [comment]
This is stale.  I'm moving it to the issue tracker.
