### ISSUE TITLE
DCDReporter error in Python 3. 

### ISSUE THREAD

**Issue by msultan** [pandegroup/openmm#782]
I tried installing Openmm in python 3.4. While it installed just fine(without any errors) and ran simulations for me too, the DCD reporter is throwing an error. The same script works just fine on the same hardware for python 2.7. I am not sure if I need to rebuild my installation or if this is an actual bug but I think it might be the latter. 
Cheers,
Muneeb 
```
Traceback (most recent call last):
  File "long_simulate.py", line 88, in <module>
    simulate_run(options.d)
  File "long_simulate.py", line 70, in simulate_run
    simulation.step(5000000)
  File "/home/msultan/software/miniconda/envs/py3k/lib/python3.4/site-packages/simtk/openmm/app/simulation.py", line 127, in step
    reporter.report(self, state)
  File "/home/msultan/software/miniconda/envs/py3k/lib/python3.4/site-packages/simtk/openmm/app/dcdreporter.py", line 75, in report
    self._dcd = DCDFile(self._out, simulation.topology, simulation.integrator.getStepSize(), 0, self._reportInterval)
  File "/home/msultan/software/miniconda/envs/py3k/lib/python3.4/site-packages/simtk/openmm/app/dcdfile.py", line 73, in __init__
    header = struct.pack('<i4c9if', 84, 'C', 'O', 'R', 'D', 0, firstStep, interval, 0, 0, 0, 0, 0, 0, dt)
struct.error: char format requires a bytes object of length 1
```

**Comment by mpharrigan** [comment]
I thought this was fixed with #715

**Comment by mpharrigan** [comment]
p.s. surround tracebacks with triple backticks: ``` for code formatting

**Comment by msultan** [comment]
Yep, that should solve it. Thanks!
