### ISSUE TITLE
Uninformative lepton errors from Custom*Force classes

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#798]
It looks like it's possible to run into lepton errors with malformed `Custom*Force` energy expressions that lead to noninformative (or at least hard to figure out) exception messages.  Here's an example:

```python
>>> from simtk import openmm
>>> force = openmm.CustomBondForce('r**2')
>>> system = openmm.System()
>>> system.addForce(force)
0
>>> system.addParticle(1)
0
>>> integrator = openmm.VerletIntegrator(1.0)
>>> context = openmm.Context(system, integrator)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4892, in __init__
    this = _openmm.new_Context(*args)
Exception: Parse error: unexpected token: *
```
It would be great if there was at least some clue as to which `Force` object was generating this error, and that this was due to a malformed lepton expression in the energy expression for the `Custom*Force` object.

**Comment by jchodera** [comment]
Thanks!
